(define (c amount)
  (define (cc amount n)
    (cond ((= amount 0) 1)
          ((or (< amount 0)
               (= n 0)) 0)
          (else (+ (cc amount (- n 1))
                   (cc (- amount (first n)) n)))))
  (define (first n)
    (cond ((= 1 n) 1)
          ((= 2 n) 5)
          ((= 3 n) 10)
          ((= 4 n) 25)
          ((= 5 n) 50))) 
    
  (cc amount 5))
